/**
 * §7 — Boundaries.
 *
 * "The rule underneath all of these: an allow list shapes the easy path; only a
 * deny rule enforces a boundary." Measured: blocked on Write, an agent immediately
 * attempted the same write through the shell. So everything below that matters is
 * a denial, and the omissions are convenience only.
 *
 * Three independent layers, in decreasing order of how much they are trusted:
 *
 *   1. Workspace confinement. The CLI confines file tools to the working directory
 *      plus whatever --add-dir names. Another agent's home is not merely denied,
 *      it is not in the workspace at all. This is the layer that makes L5 and X4
 *      real rather than documented.
 *   2. Deny rules, written into the agent's own directory (X6) and passed with
 *      --settings. These carry X3's table and the comms-root read-only rule (T6).
 *   3. Tool-level denials on argv (--disallowedTools) and a constrained built-in
 *      set (--tools). X1 lives here: Bash is denied, not omitted.
 *
 * X7 is why none of these is trusted alone: "An agent directory may already contain
 * a permission-granting hook installed for unrelated reasons... an agent launched
 * with a restrictive permission mode can self-approve by typing the prefix." A hook
 * in the target directory can return an allow decision that overrides layer 2. It
 * cannot conjure a tool that layer 3 removed, and it cannot reach outside the
 * workspace of layer 1. That ordering is the reason for the redundancy.
 */
import path from 'node:path';
import type { Agent, Config } from '../config/load.js';
import { MCP_TOOL_ID } from '../contract/names.js';

/**
 * X1 — "Shell tools are explicitly denied for every orchestrator-dispatched agent.
 * Not omitted from an allow list — denied. A shell reaches every path the account
 * can reach, so a path-scoped write permission is worthless beside one."
 *
 * Every tool that reaches a shell, not just the obvious one. Omitting the readers
 * would leave a way to observe output from a shell started some other way.
 */
export const SHELL_TOOLS = ['Bash', 'BashOutput', 'KillShell', 'KillBash'] as const;

/**
 * X3 — "published reports show subagents executing tools absent from the project
 * allowlist with no permission check." A subagent is a second permission surface
 * this application cannot see into, so it is denied unless a roster entry opts in.
 */
export const SUBAGENT_TOOLS = ['Task', 'Agent'] as const;

/** X3's deny-write table, relative to the agent's own home. */
export const SELF_GRANT_PATHS = [
  '.claude/settings.json',
  '.claude/settings.local.json',
  '.mcp.json',
  '.claude/agents/**',
  // Generated by this application and passed with --settings. It carries the deny
  // rules themselves, so it belongs in the same column as settings.json for
  // exactly the reason X3 gives.
  '.claude/orchestrator.settings.json',
  // Generated by this application and passed with --mcp-config. It names a command
  // and its arguments, so a write here is a self-granted *execution* on the next
  // invocation — the same column as settings.json, for a stronger reason.
  '.claude/orchestrator.mcp.json',
] as const;

/**
 * X3's writable row: "Instructions the model reads, not code the harness executes.
 * Worst case is a bad instruction, which is a quality problem."
 *
 * X3a qualifies it: "Skill-write is safe because shell is denied, not on its own...
 * If X1 is relaxed for some agent, skill-write becomes an escalation path for that
 * agent. The two requirements hold each other up; neither is relaxed without
 * re-checking the other." So this is the one place the two are checked together.
 */
export const SKILL_PATHS = ['.claude/skills/**', '.claude/commands/**'] as const;

/** Tools that write to the filesystem, and therefore need path-scoped denials. */
const WRITE_TOOLS = ['Write', 'Edit', 'MultiEdit', 'NotebookEdit'] as const;

/**
 * Tools that leave the machine. Neither is in the default set, and both need an
 * explicit allow rule as well as a place in `--tools` — see the comment at the point
 * they are granted, which records what happens when only one of the two is done.
 */
export const NETWORK_TOOLS = ['WebSearch', 'WebFetch'] as const;

/**
 * Permission-rule path syntax: the absolute path, forward slashes, nothing in front.
 *
 * It used to emit a `//` prefix, on the belief that this is how Claude Code spells an
 * absolute rule. **Measured on 2.1.239, Windows, and the result is worth stating
 * plainly: a `//`-prefixed rule matches nothing at all.** Three spellings of the same
 * grant were given to a live agent, one directory each, and the disk was checked
 * rather than the agent's report:
 *
 *     Write(//C:/…/doubleSlash/**)     nothing written
 *     Write(../../forms/relative/**)   nothing written
 *     Write(C:/…/bareAbsolute/**)      written
 *
 * Then the same question for denials, because that is the direction that matters. A
 * directory allowed by the bare form and denied by the `//` form was **written to**;
 * a directory allowed and denied by the bare form was not. So the prefix did not make
 * a rule strict or lax — it made the rule inert.
 *
 * What that meant while it was wrong: the write denial on the comms root, and the one
 * on read-only document stores, were both decoration. Nothing was exposed, because a
 * write outside the agent's home is refused when *no* rule permits it and none did —
 * but that is protection by accident, and this file's own header says an omission is
 * not a boundary. The denials are real now.
 *
 * The self-grant denials were never affected: each is emitted twice, and the
 * working-directory-relative twin (`.claude/settings.json`) is the one that matched.
 *
 * Rules use forward slashes on every platform. That is a rule *format*, not stored
 * state — canonical native form is what is held in memory and written to the index.
 */
export function rulePath(abs: string, suffix = ''): string {
  const forward = abs.replace(/\\/g, '/').replace(/\/+$/, '');
  return `${forward}${suffix}`;
}

/**
 * One boundary, said twice.
 *
 * `what` is the whole explanation and stands on its own: it names the tool or the
 * path, says what happens, and says why that is the safe answer. `requirement` is
 * the internal spec identifier the rule came from. That is a cross-reference, not
 * part of the explanation — useful to whoever maintains this application and
 * meaningless to anybody else.
 *
 * Two fields rather than one string, because the two readers differ. The dashboard
 * shows an operator what their checkboxes came to and sends `what` alone; the CLI's
 * dry run is read while working on this application and prints both. Interpolated
 * into a single sentence the identifier could only be removed by a regex over prose,
 * which is how "skill-write is denied because X1 is relaxed" turns into
 * "skill-write is denied because is relaxed".
 */
export interface Boundary {
  what: string;
  requirement: string | null;
}

export interface PermissionPlan {
  /** Written to <agentHome>/.claude/orchestrator.settings.json (X6). */
  settings: {
    permissions: {
      deny: string[];
      allow: string[];
      /** Directories added to the workspace beyond cwd. */
      additionalDirectories: string[];
    };
  };
  /** --disallowedTools */
  disallowedTools: string[];
  /** --allowedTools */
  allowedTools: string[];
  /** --tools, the built-in set this agent may draw from at all. */
  tools: string[];
  /** --add-dir */
  addDirs: string[];
  /** An account of every boundary, in two halves — see `Boundary`. */
  rationale: Boundary[];
}

export function buildPermissionPlan(config: Config, agent: Agent): PermissionPlan {
  const deny: string[] = [];
  const allow: string[] = [];
  const disallowedTools: string[] = [];
  const rationale: Boundary[] = [];
  const note = (requirement: string | null, what: string): void => {
    rationale.push({ requirement, what });
  };

  // ---- X1: shell -----------------------------------------------------------
  if (agent.shellAllowed) {
    // X2 — record it explicitly rather than pretending the path rules hold.
    note(
      'X2',
      `A shell is ALLOWED for "${agent.name}". Every path rule below is advisory as a result — a shell reaches whatever this account can reach — so those boundaries have to be enforced somewhere other than here.`
    );
  } else {
    for (const t of SHELL_TOOLS) {
      deny.push(t);
      disallowedTools.push(t);
    }
    note('X1', `${SHELL_TOOLS.join(', ')} are denied — not left out of a list, denied. A path-scoped write rule is worth nothing beside a shell.`);
  }

  // ---- X3: subagents -------------------------------------------------------
  if (!agent.allowSubagents) {
    for (const t of SUBAGENT_TOOLS) {
      deny.push(t);
      disallowedTools.push(t);
    }
    note('X3', 'Subagent tools are denied. A subagent definition carries its own tool grants, which this application cannot see into or restrict.');
  } else {
    note('X3', `Subagents are ALLOWED for "${agent.name}". What they may do is decided by their own definitions, outside everything on this page.`);
  }

  // ---- X3: self-granted permissions ---------------------------------------
  // Both spellings for the same reason as the outbox allow rules below, and it
  // matters more here: a deny rule that fails to match is a boundary that is not
  // there. The relative form is the one measured to match on this CLI version.
  for (const rel of SELF_GRANT_PATHS) {
    for (const tool of WRITE_TOOLS) {
      deny.push(`${tool}(${rel})`);
      deny.push(`${tool}(${rulePath(agent.home, '/' + rel)})`);
    }
  }
  note('X3', 'Writes are denied to settings.json, settings.local.json, .mcp.json and .claude/agents/. Each of those is read as configuration on the next invocation, so a write there would be this agent granting itself a permission.');

  // ---- X3a: skills, and the coupling that makes them safe ------------------
  if (agent.shellAllowed) {
    for (const rel of SKILL_PATHS) {
      for (const tool of WRITE_TOOLS) {
        deny.push(`${tool}(${rel})`);
        deny.push(`${tool}(${rulePath(agent.home, '/' + rel)})`);
      }
    }
    note('X3a', 'Writing its own skills is DENIED, because this agent has a shell. A skill telling the agent to run a script is inert with nothing to run it; with a shell it becomes a way to escalate. The two settings hold each other up, which is why relaxing one closes the other.');
  } else {
    note('X3a', 'Writing its own skills is permitted, inside its own directory. That is safe only because the shell is denied above; either way the skill files are diffed mechanically after every run.');
  }

  // ---- X3: MCP -------------------------------------------------------------
  if (!agent.allowMcp) {
    note('X3', 'The only MCP servers connected are the ones this application names. Left alone, a non-interactive session connects whatever the directory\'s own .mcp.json lists, with nothing asking first.');
  } else {
    note('X3', `Its own MCP servers are ALLOWED for "${agent.name}". Entries in its .mcp.json start processes, and in a non-interactive run nothing asks first.`);
  }

  // The one MCP tool this application offers. Allowed by its fully-qualified name so
  // the grant cannot widen if another server is ever connected: it names one tool on
  // one server, not the MCP surface.
  //
  // It is not added to --tools. That flag selects from the CLI's built-in set, and
  // an MCP tool is not in it; whether the tool is reachable at all is what
  // `orchestrator probe-mcp` measures rather than assumes.
  if (config.contract.mcp) {
    allow.push(MCP_TOOL_ID);
    note('T6', `${MCP_TOOL_ID} is allowed. The agent supplies the fields and this application writes the message file, so there is no format for the agent to get wrong.`);
  }

  // ---- L5, X4, X6: where this agent may write -----------------------------
  //
  // Both spellings, deliberately. *Measured on Claude Code 2.1.237, Windows:* an
  // absolute-form rule alone (`Write(//C:/.../outbox/**)`) did not match, and the
  // agent's write into its own outbox was denied — the exact X4 failure mode, "a
  // system that looks like it works and does nothing". The working-directory-relative
  // form is what the CLI matches reliably, and cwd is always the agent's home (D2),
  // so `outbox/**` is unambiguous. The absolute form is kept alongside it because it
  // costs nothing and is what a future CLI version is most likely to standardise on.
  const outbox = agent.outbox;
  const outboxRel = path.relative(agent.home, outbox).replace(/\\/g, '/');
  for (const t of WRITE_TOOLS) {
    allow.push(`${t}(${outboxRel}/**)`);
    allow.push(`${t}(${rulePath(outbox, '/**')})`);
  }
  note('L5', `It delivers its messages into one outbox, inside its own home: ${outbox}`);

  // ---- The agent's ordinary work, if the operator has allowed it --------------
  //
  // L5 is about where the *message* goes, and the outbox-only default was read as a
  // statement about everything the agent writes. It is not, and the gap showed up as
  // an agent asked to produce a document being unable to save one: `Write` to its own
  // home was denied, and the only trace was an apology in the message it did manage
  // to send.
  //
  // The deny rules above are emitted before this and are unconditional, so the
  // self-grant paths stay shut — deny beats allow, and that ordering is what makes a
  // home-wide grant safe to offer at all rather than a way to hand X3 back.
  if (agent.homeWritable) {
    for (const t of WRITE_TOOLS) {
      allow.push(`${t}(**)`);
      allow.push(`${t}(${rulePath(agent.home, '/**')})`);
    }
    note(
      'X3',
      `Writing is ALLOWED anywhere in its own home: ${agent.home}. The denials above still apply on top of this — a denial always beats a permission — so the settings files stay shut. Other agents' homes are outside this agent's workspace entirely.`
    );
  } else {
    note(
      'L5',
      'Writing is confined to the outbox. This agent cannot save a working file in its own home — tick "anywhere in its own home directory" if its job is to produce documents there.'
    );
  }

  // ---- The network tools, which need saying twice --------------------------
  //
  // *Measured on Claude Code 2.1.239:* WebSearch present in `--tools` and absent
  // from `--allowed-tools` is **denied**, and the denial is silent from the prompt's
  // side — the agent reports "no web search tool is available" and writes its answer
  // from memory, which reads as an agent that chose not to look rather than one that
  // was refused. That is the exact failure this file's header calls the worst kind.
  //
  // The reason is `--permission-mode dontAsk`: a tool with no allow rule needs a
  // prompt, and there is nobody to answer it. Every other tool an agent uses is
  // either path-scoped above or approved by workspace confinement; these two reach
  // outside it and so have neither.
  for (const t of NETWORK_TOOLS) {
    if (agent.tools.includes(t)) {
      allow.push(t);
      note(
        null,
        `${t} is allowed. It reaches the network, so it has to be granted by name; without that it would sit in the agent's tool list looking available and be refused the moment it was used.`
      );
    }
  }

  // ---- T6, L2: the comms root is readable, never writable ------------------
  // "Agents never write into the comms root; the application owns it entirely."
  for (const tool of WRITE_TOOLS) {
    deny.push(`${tool}(${rulePath(config.commsRoot, '/**')})`);
  }
  allow.push(`Read(${rulePath(config.commsRoot, '/**')})`);
  note('T6/L2', 'The ledger is readable and never writable. Only this application writes to it.');

  // ---- X4: directories outside the home, and what may happen in them -------
  //
  // A directory the agent may write is granted; one it may only read is granted for
  // reading and *denied* for writing. That denial is not redundant with the omission
  // beside it: both directories are in the workspace, because they have to be for
  // the agent to reach them at all, and inside the workspace an omission is only an
  // omission. It is also the one place a wrong rule spelling would not show up —
  // see `rulePath`, where exactly that was true until it was measured.
  for (const p of agent.paths) {
    // Write without read is not a thing the filesystem offers, and pretending
    // otherwise would produce an agent that can overwrite a file it cannot open.
    if (p.read || p.write) allow.push(`Read(${rulePath(p.path, '/**')})`);
    for (const tool of WRITE_TOOLS) {
      const rule = `${tool}(${rulePath(p.path, '/**')})`;
      if (p.write) allow.push(rule);
      else deny.push(rule);
    }
  }
  const readOnly = agent.paths.filter((p) => !p.write).map((p) => p.path);
  const writable = agent.paths.filter((p) => p.write).map((p) => p.path);
  if (readOnly.length) {
    note('X4', `Outside its home it may read but never write: ${readOnly.join(', ')}`);
  }
  if (writable.length) {
    note(
      'X4',
      `Outside its home it may read AND write: ${writable.join(', ')}. Nothing here is inside another agent's home unless you put it there, and this application does not check that for you.`
    );
  }

  // ---- Layer 1: the workspace ---------------------------------------------
  // Every other agent's home is absent from this list, which is stronger than a
  // deny rule: file tools cannot address a path outside the workspace at all.
  // Layer 1. A directory absent from here cannot be addressed by a file tool at
  // all, whatever the rules say — which is why a read-only entry still appears.
  const addDirs = [config.commsRoot, ...agent.paths.map((p) => p.path)];

  const others = config.agents.filter((a) => a.name !== agent.name);
  if (others.length) {
    note('L5/X4', `${others.length} other agent director${others.length === 1 ? 'y is' : 'ies are'} outside this agent's workspace entirely — not denied by a rule, simply not addressable.`);
  }

  // ---- Layer 3: the built-in tool set -------------------------------------
  // Belt to the deny rules' braces. A tool absent here cannot be reached even by a
  // hook that returns an allow decision (X7).
  const tools = agent.tools.filter((t) => !disallowedTools.includes(t));
  if (agent.shellAllowed && !tools.includes('Bash')) tools.push('Bash');

  return {
    settings: {
      permissions: {
        deny: dedupe(deny),
        allow: dedupe(allow),
        additionalDirectories: addDirs,
      },
    },
    disallowedTools: dedupe(disallowedTools),
    allowedTools: dedupe(allow),
    tools: dedupe(tools),
    addDirs,
    rationale,
  };
}

/** The path the generated settings file is written to, in the agent's own home (X6). */
export function settingsPathFor(agent: Agent): string {
  return path.join(agent.home, '.claude', 'orchestrator.settings.json');
}

function dedupe(xs: string[]): string[] {
  return [...new Set(xs)];
}
