/**
 * §7 — Boundaries.
 *
 * "The rule underneath all of these: an allow list shapes the easy path; only a
 * deny rule enforces a boundary." Measured: blocked on Write, an agent immediately
 * attempted the same write through the shell. So everything below that matters is
 * a denial, and the omissions are convenience only.
 *
 * Three independent layers, in decreasing order of how much they are trusted:
 *
 *   1. Workspace confinement. The CLI confines file tools to the working directory
 *      plus whatever --add-dir names. Another agent's home is not merely denied,
 *      it is not in the workspace at all. This is the layer that makes L5 and X4
 *      real rather than documented.
 *   2. Deny rules, written into the agent's own directory (X6) and passed with
 *      --settings. These carry X3's table and the comms-root read-only rule (T6).
 *   3. Tool-level denials on argv (--disallowedTools) and a constrained built-in
 *      set (--tools). X1 lives here: Bash is denied, not omitted.
 *
 * X7 is why none of these is trusted alone: "An agent directory may already contain
 * a permission-granting hook installed for unrelated reasons... an agent launched
 * with a restrictive permission mode can self-approve by typing the prefix." A hook
 * in the target directory can return an allow decision that overrides layer 2. It
 * cannot conjure a tool that layer 3 removed, and it cannot reach outside the
 * workspace of layer 1. That ordering is the reason for the redundancy.
 */
import path from 'node:path';
import type { Agent, Config } from '../config/load.js';
import { MCP_TOOL_ID } from '../contract/names.js';

/**
 * X1 — "Shell tools are explicitly denied for every orchestrator-dispatched agent.
 * Not omitted from an allow list — denied. A shell reaches every path the account
 * can reach, so a path-scoped write permission is worthless beside one."
 *
 * Every tool that reaches a shell, not just the obvious one. Omitting the readers
 * would leave a way to observe output from a shell started some other way.
 */
export const SHELL_TOOLS = ['Bash', 'BashOutput', 'KillShell', 'KillBash'] as const;

/**
 * X3 — "published reports show subagents executing tools absent from the project
 * allowlist with no permission check." A subagent is a second permission surface
 * this application cannot see into, so it is denied unless a roster entry opts in.
 */
export const SUBAGENT_TOOLS = ['Task', 'Agent'] as const;

/** X3's deny-write table, relative to the agent's own home. */
export const SELF_GRANT_PATHS = [
  '.claude/settings.json',
  '.claude/settings.local.json',
  '.mcp.json',
  '.claude/agents/**',
  // Generated by this application and passed with --settings. It carries the deny
  // rules themselves, so it belongs in the same column as settings.json for
  // exactly the reason X3 gives.
  '.claude/orchestrator.settings.json',
  // Generated by this application and passed with --mcp-config. It names a command
  // and its arguments, so a write here is a self-granted *execution* on the next
  // invocation — the same column as settings.json, for a stronger reason.
  '.claude/orchestrator.mcp.json',
] as const;

/**
 * X3's writable row: "Instructions the model reads, not code the harness executes.
 * Worst case is a bad instruction, which is a quality problem."
 *
 * X3a qualifies it: "Skill-write is safe because shell is denied, not on its own...
 * If X1 is relaxed for some agent, skill-write becomes an escalation path for that
 * agent. The two requirements hold each other up; neither is relaxed without
 * re-checking the other." So this is the one place the two are checked together.
 */
export const SKILL_PATHS = ['.claude/skills/**', '.claude/commands/**'] as const;

/** Tools that write to the filesystem, and therefore need path-scoped denials. */
const WRITE_TOOLS = ['Write', 'Edit', 'MultiEdit', 'NotebookEdit'] as const;

/**
 * Permission-rule path syntax. Claude Code takes an absolute path as `//` followed
 * by the path with forward slashes; on Windows that is `//C:/YourDirectory/...`. Rules use
 * forward slashes regardless of platform, which is a rule *format*, not stored
 * state, so T5 is untouched — canonical native form is what we hold in memory and
 * write to the index.
 */
export function rulePath(abs: string, suffix = ''): string {
  const forward = abs.replace(/\\/g, '/').replace(/\/+$/, '');
  return `//${forward}${suffix}`;
}

export interface PermissionPlan {
  /** Written to <agentHome>/.claude/orchestrator.settings.json (X6). */
  settings: {
    permissions: {
      deny: string[];
      allow: string[];
      /** Directories added to the workspace beyond cwd. */
      additionalDirectories: string[];
    };
  };
  /** --disallowedTools */
  disallowedTools: string[];
  /** --allowedTools */
  allowedTools: string[];
  /** --tools, the built-in set this agent may draw from at all. */
  tools: string[];
  /** --add-dir */
  addDirs: string[];
  /** Human-readable account of every boundary and the requirement behind it. */
  rationale: string[];
}

export function buildPermissionPlan(config: Config, agent: Agent): PermissionPlan {
  const deny: string[] = [];
  const allow: string[] = [];
  const disallowedTools: string[] = [];
  const rationale: string[] = [];

  // ---- X1: shell -----------------------------------------------------------
  if (agent.shellAllowed) {
    // X2 — record it explicitly rather than pretending the path rules hold.
    rationale.push(
      `X2: shell is ALLOWED for "${agent.name}". Its file boundaries below are advisory and must be enforced somewhere else.`
    );
  } else {
    for (const t of SHELL_TOOLS) {
      deny.push(t);
      disallowedTools.push(t);
    }
    rationale.push(`X1: ${SHELL_TOOLS.join(', ')} denied — not omitted, denied.`);
  }

  // ---- X3: subagents -------------------------------------------------------
  if (!agent.allowSubagents) {
    for (const t of SUBAGENT_TOOLS) {
      deny.push(t);
      disallowedTools.push(t);
    }
    rationale.push('X3: subagent tools denied — subagent definitions carry tool grants this application cannot see.');
  } else {
    rationale.push(`X3: subagents are ALLOWED for "${agent.name}". Their tool grants are outside this application's permission model.`);
  }

  // ---- X3: self-granted permissions ---------------------------------------
  // Both spellings for the same reason as the outbox allow rules below, and it
  // matters more here: a deny rule that fails to match is a boundary that is not
  // there. The relative form is the one measured to match on this CLI version.
  for (const rel of SELF_GRANT_PATHS) {
    for (const tool of WRITE_TOOLS) {
      deny.push(`${tool}(${rel})`);
      deny.push(`${tool}(${rulePath(agent.home, '/' + rel)})`);
    }
  }
  rationale.push('X3: writes denied to settings.json, settings.local.json, .mcp.json and .claude/agents/ — each one executes, so a write there is a self-granted permission on the next invocation.');

  // ---- X3a: skills, and the coupling that makes them safe ------------------
  if (agent.shellAllowed) {
    for (const rel of SKILL_PATHS) {
      for (const tool of WRITE_TOOLS) {
        deny.push(`${tool}(${rel})`);
        deny.push(`${tool}(${rulePath(agent.home, '/' + rel)})`);
      }
    }
    rationale.push('X3a: skill-write DENIED because X1 is relaxed for this agent. A skill instructing the agent to run a script is inert with nothing to run it; with a shell it is an escalation path. The two requirements hold each other up.');
  } else {
    rationale.push('X3a: skill-write permitted in this agent\'s own directory, and safe only because shell is denied above. D13 diffs it mechanically regardless (T8).');
  }

  // ---- X3: MCP -------------------------------------------------------------
  if (!agent.allowMcp) {
    rationale.push('X3: --strict-mcp-config, so the only MCP servers connected are the ones this application names. Non-interactive sessions otherwise connect .mcp.json servers in a directory never trusted.');
  } else {
    rationale.push(`X3: MCP is ALLOWED for "${agent.name}". .mcp.json entries in its own directory start processes without an approval step in non-interactive mode.`);
  }

  // The one MCP tool this application offers. Allowed by its fully-qualified name so
  // the grant cannot widen if another server is ever connected: it names one tool on
  // one server, not the MCP surface.
  //
  // It is not added to --tools. That flag selects from the CLI's built-in set, and
  // an MCP tool is not in it; whether the tool is reachable at all is what
  // `orchestrator probe-mcp` measures rather than assumes.
  if (config.contract.mcp) {
    allow.push(MCP_TOOL_ID);
    rationale.push(`T6: ${MCP_TOOL_ID} allowed — the agent supplies fields and the application writes the message file, so there is no format for it to get wrong.`);
  }

  // ---- L5, X4, X6: where this agent may write -----------------------------
  //
  // Both spellings, deliberately. *Measured on Claude Code 2.1.237, Windows:* an
  // absolute-form rule alone (`Write(//C:/.../outbox/**)`) did not match, and the
  // agent's write into its own outbox was denied — the exact X4 failure mode, "a
  // system that looks like it works and does nothing". The working-directory-relative
  // form is what the CLI matches reliably, and cwd is always the agent's home (D2),
  // so `outbox/**` is unambiguous. The absolute form is kept alongside it because it
  // costs nothing and is what a future CLI version is most likely to standardise on.
  const outbox = agent.outbox;
  const outboxRel = path.relative(agent.home, outbox).replace(/\\/g, '/');
  for (const t of WRITE_TOOLS) {
    allow.push(`${t}(${outboxRel}/**)`);
    allow.push(`${t}(${rulePath(outbox, '/**')})`);
  }
  rationale.push(`L5: one outbox, inside this agent's own home — ${outbox} (allowed as both "${outboxRel}/**" and the absolute form; the relative form is the one measured to match)`);

  // ---- T6, L2: the comms root is readable, never writable ------------------
  // "Agents never write into the comms root; the application owns it entirely."
  for (const tool of WRITE_TOOLS) {
    deny.push(`${tool}(${rulePath(config.commsRoot, '/**')})`);
  }
  allow.push(`Read(${rulePath(config.commsRoot, '/**')})`);
  rationale.push('T6/L2: the comms root is readable and never writable. Only the application writes the ledger index.');

  // ---- X4: reads are scoped to whatever document store it needs ------------
  for (const p of agent.readPaths) {
    allow.push(`Read(${rulePath(p, '/**')})`);
    for (const tool of WRITE_TOOLS) deny.push(`${tool}(${rulePath(p, '/**')})`);
  }
  if (agent.readPaths.length) {
    rationale.push(`X4: read-only document stores — ${agent.readPaths.join(', ')}`);
  }

  // ---- Layer 1: the workspace ---------------------------------------------
  // Every other agent's home is absent from this list, which is stronger than a
  // deny rule: file tools cannot address a path outside the workspace at all.
  const addDirs = [config.commsRoot, ...agent.readPaths];

  const others = config.agents.filter((a) => a.name !== agent.name);
  if (others.length) {
    rationale.push(`L5/X4: ${others.length} other agent director${others.length === 1 ? 'y is' : 'ies are'} outside this agent's workspace entirely, not merely denied.`);
  }

  // ---- Layer 3: the built-in tool set -------------------------------------
  // Belt to the deny rules' braces. A tool absent here cannot be reached even by a
  // hook that returns an allow decision (X7).
  const tools = agent.tools.filter((t) => !disallowedTools.includes(t));
  if (agent.shellAllowed && !tools.includes('Bash')) tools.push('Bash');

  return {
    settings: {
      permissions: {
        deny: dedupe(deny),
        allow: dedupe(allow),
        additionalDirectories: addDirs,
      },
    },
    disallowedTools: dedupe(disallowedTools),
    allowedTools: dedupe(allow),
    tools: dedupe(tools),
    addDirs,
    rationale,
  };
}

/** The path the generated settings file is written to, in the agent's own home (X6). */
export function settingsPathFor(agent: Agent): string {
  return path.join(agent.home, '.claude', 'orchestrator.settings.json');
}

function dedupe(xs: string[]): string[] {
  return [...new Set(xs)];
}
